name: firebase_app_indexing
description: Firebase app indexing plugin,
version: 0.2.0
homepage: https://github.com/wiseminds/firebase_app_indexing

environment:
  sdk: ">=3.0.0 <3.5.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.wiseminds.firebase_app_indexing
        pluginClass: FirebaseAppIndexingPlugin
      ios:
        pluginClass: FirebaseAppIndexingPlugin
